import Head from 'next/head'
import App from "../src/App";


function index() {
  return (
    <div>
      <Head>
        <title>Meet.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <App pageName='Home'/>
    </div>
  )
}

export default index;